config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'orders#index'

  resources :clients
  resources :products
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :orders, dependent: :destroy

  validates :name, presence: true
  validates :number, presence: true #, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :client
  has_many :orders_products
  has_many :products, through: :orders_products

  accepts_nested_attributes_for :client, reject_if: :all_blank
  accepts_nested_attributes_for :orders_products, reject_if: :all_blank

  validates :count, presence: true, uniqueness: true
end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders_products
  has_many :orders, through: :orders_products

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :load_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client
    else
      render :new
    end
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def load_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:number, :name, :postcode)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
    @client = @order.build_client
  end

  def new
    @order = Order.new
    @order.build_client
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    #Client.find_by_created_at(number: @order.number).nil?
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def load_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:count, :quantity, order_product_attributes: %i[product_id quantity], client_attributes: %i[number name postcode])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/clients/_client.slim
tr
  td= client.number
  td= client.name
  td= client.postcode
  td= link_to 'Show', client_path(client)
  td= link_to 'Edit', edit_client_path(client)
  td= link_to 'Delete', client_path(client), method: :delete, data: { confirm: 'Are you sure?' }

app/views/clients/_form.slim
= form_with model: @client do |f|
  = render 'shared/errors', resource: @client

  p
    = f.label :number
    = f.text_field :number
  p
    = f.label :name
    = f.text_field :name
  p
    = f.label :postcode
    = f.text_field :postcode

  p= f.submit

app/views/clients/edit.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Edit Client

  = render 'form'
  = link_to 'Back', clients_path

app/views/clients/index.slim
.m-4
  h3.mb-4.mt-4.text-center
    | Client

  p= link_to 'New client', new_client_path

  table.table.table-striped.table-bordered.table-hover.text-center
    tr
      th Number
      th Name
      th Postcode
      th[colspan='3']
        | Actions

    = render @clients

  p= link_to 'Orders', orders_path
  p= link_to 'Products', products_path

app/views/clients/new.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Create new Client

  = render 'form'
  = link_to 'Back', clients_path

app/views/clients/show.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Client

  p
    strong
      | Number:&nbsp
      = @client.number
  p
    strong
      | Name:&nbsp
      = @client.name
  p
    strong
      | Postcode:&nbsp
      = @client.postcode

  = link_to 'Edit', edit_client_path(@client)
  |  |
  = link_to ' Back', clients_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OttoOrder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.slim
= form_with model: @order do |f|
  = render 'shared/errors', resource: @order

  p
    = f.label :count
    = f.text_field :count

  = f.fields_for :client do |c|
    p
      = c.label :number, 'Client number'
      = c.text_field :number
    p
      = c.label :name
      = c.text_field :name
    p
      = c.label :postcode
      = c.text_field :postcode

  = f.fields_for :order_product do |op|
    p
      = op.label :product_id, 'Product'
      = op.text_field :product_id
    p
      = op.label :quantity
      = op.text_field :quantity
    //.links
    //  = link_to_add_association 'add product', f, :order_product
  p= f.submit

app/views/orders/_order.slim
tr
  td= order.count
  td= link_to 'Show', order_path(order)
  td= link_to 'Edit', edit_order_path(order)
  td= link_to 'Delete', order_path(order), method: :delete, data: { confirm: 'Are you sure?' }

app/views/orders/edit.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Edit Order

  = render 'form'
  = link_to 'Back', orders_path

app/views/orders/index.slim
.m-4
  h3.mb-4.mt-4.text-center
    | Orders

  p= link_to 'New order', new_order_path

  table.table.table-striped.table-bordered.table-hover.text-center
    tr
      th Count
      th[colspan='3']
        | Actions

    = render @orders

  p= link_to 'Products', products_path
  p= link_to 'Clients', clients_path

app/views/orders/new.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Create new Order

  = render 'form'
  = link_to 'Back', orders_path

app/views/orders/show.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Order

  p
    strong
      | Count:&nbsp
      = @order.count
  p
    strong
      | Client number:&nbsp
      = @order.client.number
  p
    strong
      | Client name:&nbsp
      = @order.client.name
  p
    strong
      | Client postcode:&nbsp
      = @order.client.postcode
  p
    strong
      | ID product:&nbsp
      = @order.products.select('products.*, orders_products.product_id').first
  p
    strong
      | Quantity:&nbsp
      = @order.products.select('products.*, orders_products.quantity').first

  = link_to 'Edit', edit_order_path(@order)
  |  |
  = link_to ' Back', orders_path

app/views/products/_form.slim
= form_with model: @product do |f|
  = render 'shared/errors', resource: @product

  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_field :body

  p= f.submit

app/views/products/_product.slim
tr
  td= product.title
  td= product.body
  td= link_to 'Show', product_path(product)
  td= link_to 'Edit', edit_product_path(product)
  td= link_to 'Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/edit.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Edit Product

  = render 'form'
  = link_to 'Back', products_path

app/views/products/index.slim
.m-4
  h3.mb-4.mt-4.text-center
    | Product

  p= link_to 'New product', new_product_path

  table.table.table-striped.table-bordered.table-hover.text-center
    tr
      th Title
      th Body
      th[colspan='3']
        | Actions

    = render @products

  p= link_to 'Orders', orders_path
  p= link_to 'Clients', clients_path

app/views/products/new.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Create new Product

  = render 'form'
  = link_to 'Back', products_path

app/views/products/show.slim
.m-4
  h4.mb-4.mt-4.text-left
    | Product

  p
    strong
      | Title:&nbsp
      = @product.title
  p
    strong
      | Body:&nbsp
      = @product.body

  = link_to 'Edit', edit_product_path(@product)
  |  |
  = link_to ' Back', products_path

app/views/shared/_errors.slim
- if resource.errors.present?
  div
    h4
      = "#{resource.errors.count} error(s) detected: "
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/shared/_flash.slim
- flash.each do |key, message|
  = content_tag :p, message, class: "flash #{key}"